import { theme } from "@/theme/theme";
import { ChakraProvider } from "@chakra-ui/react";
import Provider from "./Provider";

export const metadata = {
    title: "veluriyaのサイト",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ja">
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
